### PR TITLE
Add passive mode touch events, calms Lighthouse

### PR DESCRIPTION
**Pull request by inoas**
Refs:
https://github.com/Mango/slideout/pull/291
https://github.com/Mango/slideout/pull/289
https://github.com/Mango/slideout/pull/267

### CODE REVIEW

**Comment by inoas** [comment]
I am using `npm install --save inoas/slideout#patch-1` until this gets merged.

Edit: Somehow npm/node didnt eat the above thing correctly. This works in package.json `"slideout": "git://github.com/inoas/slideout.git#patch-1",`

_Note: You should use your own fork of my fork to be on the safe side, if you go the same route_

**Comment by inoas** [comment]
@pazguille any chance to merge this rather soon?

**Comment by inoas** [comment]
I ran tests, hints, fixed a preexisting CS issue, ran build - now it should be ok.

**Comment by inoas** [comment]
@pazguille Do you still in any way maintain this, at least eventually consider some PRs to merge?
That would be so kind.

**Comment by inoas** [comment]
Ping @pazguille - *hope*!

**Comment by htstudios** [comment]
Any news?

**Comment by paskal** [comment]
@pazguille gentle ping for review and merge.

**Comment by inoas** [comment]
kinda dead.

**Pull request closed without merging**
