### PR TITLE
Add new option `ignore` for disable dragging on some elements

### LINKED ISSUE #144: Is it possible to skip some elements on page?
So if we have slideshow with swipe functions, think it's better if slide out skip that element. Is this possible?

### PR DESCRIPTION
**Pull request by LoicMahieu**
Fix #144

### CODE REVIEW

**Comment by brianium** [comment]
:+1:

**Comment by slzr** [comment]
:+1:

**Comment by slzr** [comment]
:+1: this works? when will be merged?

**Comment by LoicMahieu** [comment]
@slzr Sure it works :) Waiting for review...

**Comment by LoicMahieu** [comment]
@pazguille Any chance to be reviewed :) ? Thanks.

**Pull request closed without merging**
